### ISSUE TITLE
Error when running with Python 3.5

### ISSUE THREAD

**Issue by leotada** [Moguri/BlenderPanda#16]
Fedora Linux 24 - 64bits
Panda 1.9.2
Python 3.5.1

```
bash-4.3$ python3 main.py 
Known pipe types:
  glxGraphicsPipe
(all display modules loaded.)
Starting build
Read assets from: /home/leonardo/Projetos/PandaTeste/assets/
Export them to: /home/leonardo/Projetos/PandaTeste/game/assets/
Ignoring file patterns: ['*.blend1', '*.blend2']
Build took 0.0002s
Traceback (most recent call last):
  File "main.py", line 20, in <module>
    app = GameApp()
  File "main.py", line 16, in __init__
    blenderpanda.init(self)
  File "/home/leonardo/Projetos/PandaTeste/game/blenderpanda/bpbase.py", line 21, in init
    base._bpbase = BPBase(base, config)
  File "/home/leonardo/Projetos/PandaTeste/game/blenderpanda/bpbase.py", line 8, in __init__
    self.rendermanager = create_render_manager(base, config)
  File "/home/leonardo/Projetos/PandaTeste/game/blenderpanda/rendermanager.py", line 38, in create_render_manager
    mod = SourceFileLoader("render_plugin", path).load_module()
  File "<frozen importlib._bootstrap_external>", line 385, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 806, in load_module
  File "<frozen importlib._bootstrap_external>", line 665, in load_module
  File "<frozen importlib._bootstrap>", line 268, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 658, in exec_module
  File "<frozen importlib._bootstrap_external>", line 763, in get_code
  File "<frozen importlib._bootstrap_external>", line 815, in get_data
IsADirectoryError: [Errno 21] Is a directory: '/home/leonardo/Projetos/PandaTeste/.'
```

**Comment by Moguri** [comment]
I do not believe this is a Python 3.5 issue. It looks like render_plugin in your pman config file is set to a directory. Could you post your pman file?

**Comment by leotada** [comment]
I just didn't know how to speak about this error.
It's here .pman:

```
[general]
name = Game
render_plugin = .

[build]
asset_dir = assets/
export_dir = game/assets/
ignore_patterns = *.blend1, *.blend2

[run]
main_file = game/main.py
auto_build = True
auto_save = True
```

**Comment by Moguri** [comment]
Sorry for the (very) late response. The render_plugin is indeed set to a directory. Either set it to a python file containing a render plugin, leave render_plugin empty (the default), or just remove the line from your pman file.

I am closing this report. If you are still running into issues, we can re-open the report.
