### ISSUE TITLE
Exporting models crashes

### ISSUE THREAD

**Issue by bkeys** [Moguri/BlenderPanda#26]
Traceback (most recent call last):
  File "/home/bkeys/.config/blender/2.78/scripts/addons/BlenderPanda/converter.py", line 678, in <module>
    converter.update(gltf_data, writing_bam=True)
  File "/home/bkeys/.config/blender/2.78/scripts/addons/BlenderPanda/converter.py", line 48, in update
    self.load_mesh(meshid, gltf_mesh, gltf_data)
  File "/home/bkeys/.config/blender/2.78/scripts/addons/BlenderPanda/converter.py", line 559, in load_mesh
    iacc = gltf_data['accessors'][iacc_name]
KeyError: u'accessor_buffer_Mesh.057_4'

**Comment by bkeys** [comment]
http://pasteall.org/blend/index.php?id=46335
Here is a model to replicate the issue with

**Comment by Moguri** [comment]
The model is exporting for me with the latest version of BlenderPanda, so I'm closing this report. If there are still issues, feel free to re-open the issue.
