### ISSUE TITLE
Rendered viewport only works once

### ISSUE THREAD

**Issue by rdb** [Moguri/BlenderPanda#31]
The rendered viewport works fine, but if I switch out of it, I get the following traceback:
```
Connected to external process
Warning: mesh meshes_wall has a primitive with no material, using an empty RenderState
Received zero-length msg header, aborting
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/rdb/.config/blender/2.79/scripts/addons/BlenderPanda/brte/brte/processor_thread.py", line 43, in run
    self.processor.destroy()
  File "/home/rdb/.config/blender/2.79/scripts/addons/BlenderPanda/brte/brte/processors/external_processor.py", line 34, in destroy
    self.listen_socket.shutdown(socket.SHUT_RDWR)
OSError: [Errno 57] Socket is not connected

Server thread has terminated, closing program
```

If I then continue to go back into the Rendered Viewport, it stays black and instead spews this onto the terminal:
```
Exception ignored in: <bound method RealTimeEngine.__del__ of <bpy_struct, PandaEngine invalid>>
Traceback (most recent call last):
  File "/home/rdb/.config/blender/2.79/scripts/addons/BlenderPanda/brte/brte/engine.py", line 148, in __del__
    G.cleanup_threads()
  File "/home/rdb/.config/blender/2.79/scripts/addons/BlenderPanda/brte/brte/engine.py", line 63, in cleanup_threads
    G.thread_converter.join()
  File "/usr/local/lib/python3.5/threading.py", line 1051, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread
Connected to external process
Received zero-length msg header, aborting
Server thread has terminated, closing program
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/rdb/.config/blender/2.79/scripts/addons/BlenderPanda/brte/brte/processor_thread.py", line 43, in run
    self.processor.destroy()
  File "/home/rdb/.config/blender/2.79/scripts/addons/BlenderPanda/brte/brte/processors/external_processor.py", line 34, in destroy
    self.listen_socket.shutdown(socket.SHUT_RDWR)
OSError: [Errno 57] Socket is not connected
```

**Comment by Moguri** [comment]
I was unable to reproduce this segfault. I held down the shift key and kept pressing Z to enter/exit the rendered viewport as fast as I could. I added some reliability tweaks (guards, try/except) in f1c9313ba1735adddd8a83f9f2ceb7205c0e42cf, would you mind re-testing this issue?

**Comment by rdb** [comment]
I still get the `OSError: [Errno 57] Socket is not connected` error upon leaving rendered viewport mode, but reentering it afterwards works now (although it takes quite long for it to display anything).  Thanks!

**Comment by Moguri** [comment]
Are you still getting this on shutdown(), or is it now on close()?

**Comment by rdb** [comment]
In `shutdown()`:
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/rdb/.config/blender/2.79/scripts/addons/BlenderPanda/brte/brte/processor_thread.py", line 43, in run
    self.processor.destroy()
  File "/home/rdb/.config/blender/2.79/scripts/addons/BlenderPanda/brte/brte/processors/external_processor.py", line 38, in destroy
    self.listen_socket.shutdown(socket.SHUT_RDWR)
OSError: [Errno 57] Socket is not connected
```
It does seem that it recovers from this failure, since your changes.  However, it might be nice to catch it more cleanly.

**Comment by Moguri** [comment]
Ah, I caught RuntimeError (the error from the threading error) instead of OSError.

**Comment by Moguri** [comment]
Can you try again with 8605195f5ce1a5eb5e30434312ca831c14a00be3?

**Comment by rdb** [comment]
Yeah, no more exception upon leaving rendered viewport mode.  Thanks!
