### ISSUE TITLE
KeyError when moving object in rendered viewport

### ISSUE THREAD

**Issue by rdb** [Moguri/BlenderPanda#32]
I created a simple scene with a plane, but when attempting to move the plane in the rendered viewport, I get this error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/rdb/.config/blender/2.79/scripts/addons/BlenderPanda/brte/brte/converter_thread.py", line 19, in run
    output = self.converter.convert(add, update, remove, view)
  File "/home/rdb/.config/blender/2.79/scripts/addons/BlenderPanda/brte/brte/converters/btf.py", line 43, in convert
    data = blendergltf.export_gltf(add_delta, self.gltf_settings)
  File "/home/rdb/.config/blender/2.79/scripts/addons/BlenderPanda/blendergltf/blendergltf.py", line 1664, in export_gltf
    ref.source[ref.prop] = refmap[(ref.blender_type, ref.blender_name)]
KeyError: ('meshes', 'Plane')
```

**Comment by rdb** [comment]
Thanks!  I can confirm that moving the object in Rendered Viewport mode now works correctly.
