### ISSUE TITLE
Error when enabling addon

### ISSUE THREAD

**Issue by typewriter1** [Moguri/BlenderPanda#44]
I downloaded the version 0.4.0 release and installed it in blender 2.79b with windows 10. However, when attempting to enable the addon by checking it in the user-preferences addons menu, this traceback was thrown:
```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\modules\addon_utils.py", line 331, in enable
    mod = __import__(module_name)
  File "C:\Users\avise\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\BlenderPanda\__init__.py", line 34, in <module>
    import pman
  File "C:\Users\avise\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\BlenderPanda\pman\pman\__init__.py", line 2, in <module>
    from .core import *
  File "C:\Users\avise\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\BlenderPanda\pman\pman\core.py", line 16, in <module>
    import pkg_resources
ImportError: No module named 'pkg_resources'
```

**Comment by Moguri** [comment]
My guess is the Python bundled with Blender does not ship with `setuptools`, which would make sense. I'll look into adding a work around for this issue.

**Comment by Moguri** [comment]
I fixed this and other issues with running Windows and created a new release (v0.4.1). Let me know if you still run into issues. I tested this new release on Windows 7.

**Comment by typewriter1** [comment]
The addon will now enable without any errors! But unfortunately there are still errors thrown when attempting to render anything or enable the "Panda 3D" renderer from the render engine dropdown. This is probably unrelated to this though.
